CREATE DATABASE TesteDev TABLESPACE = pg_default;

CREATE TABLE TABLE_CPF(
  COD_CPF SERIAL UNIQUE NOT NULL
, CPF VARCHAR(11) UNIQUE NOT NULL
, CONSTRAINT COD_PARC PRIMARY KEY (CPF)
);

CREATE TABLE TABLE_PARCEIRO(
  COD_PARC SERIAL NOT NULL
, NOME VARCHAR(50) NOT NULL
, CPF VARCHAR(11) UNIQUE NOT NULL
, ALTURA NUMERIC(10,2)
, PESO NUMERIC(10,2)
, IMC NUMERIC(10,2)
, DATACAD TIMESTAMP
, PRIMARY KEY (COD_PARC, CPF)
, CONSTRAINT CPF FOREIGN KEY(CPF) REFERENCES TABLE_CPF(CPF)
);
